# Generated by Django 5.1.4 on 2026-04-26 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('anulada', 'Anulada')], default='completada', max_length=15)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('medio_de_pago', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Opcional para ventas rápidas sin cliente registrado.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='clientes.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='productos.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.IntegerField(choices=[(1, 'Factura'), (2, 'Boleta'), (3, 'Nota de Crédito'), (4, 'Nota de Débito')])),
                ('serie', models.CharField(max_length=4)),
                ('numero', models.IntegerField()),
                ('enlace_nubefact', models.URLField(blank=True, default='')),
                ('enlace_pdf', models.URLField(blank=True, default='')),
                ('enlace_xml', models.URLField(blank=True, default='')),
                ('enlace_cdr', models.URLField(blank=True, default='')),
                ('estado_sunat', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada por SUNAT'), ('rechazada', 'Rechazada por SUNAT'), ('anulada', 'Anulada (Baja)'), ('error', 'Error al emitir')], default='pendiente', max_length=15)),
                ('aceptada_por_sunat', models.BooleanField(default=False)),
                ('sunat_descripcion', models.TextField(blank=True, default='')),
                ('codigo_hash', models.CharField(blank=True, default='', max_length=100)),
                ('cadena_qr', models.TextField(blank=True, default='')),
                ('anulada', models.BooleanField(default=False)),
                ('motivo_anulacion', models.CharField(blank=True, default='', max_length=200)),
                ('ticket_anulacion', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Comprobante Electrónico',
                'verbose_name_plural': 'Comprobantes Electrónicos',
                'unique_together': {('tipo_comprobante', 'serie', 'numero')},
            },
        ),
    ]
