# Generated by Django 5.1.4 on 2026-04-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='enlace_cdr',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='enlace_nubefact',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='enlace_pdf',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='enlace_xml',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
